### ISSUE TITLE
Integrate scala-steward and mergify to keep dependencies up-to-date

### ISSUE THREAD

**Issue by andreamarcolin** [nryanov/consul4s#10]
By opening a PR to scala-steward public instance and (eventually) adding mergify, it's way easier to keep dependencies of a public project up to date. 
It should be just a matter of opening a PR to https://github.com/scala-steward-org/repos/blob/master/repos-github.md (adding a line with the repo name) and then signing up to mergify with the github account (free for OSS).
Example configurations for Mergify:
- https://github.com/http4s/http4s/blob/main/.mergify.yml
- https://github.com/softwaremill/sttp/blob/master/.mergify.yml
- https://github.com/profunktor/redis4cats/blob/master/.mergify.yml

**Comment by nryanov** [comment]
Cool, didn't know about mergify. 
Definitely, it should be added  👍
I've opened a [PR](https://github.com/scala-steward-org/repos/pull/572) in scala-steward. After that i'll update CI and integrate mergify

Thank you!
