### ISSUE TITLE
Add scalafmt?

### ISSUE THREAD

**Issue by andreamarcolin** [nryanov/consul4s#11]
From what I can see the project contains a .scalafmt.conf file. Scalafmt sbt plugin is not present though, not sure if it's just an oversight or if the file was included by accident.

**Comment by nryanov** [comment]
Just used embedded intellij scalaftm plugin from the start :)

Plugin was added: [commit](https://github.com/nryanov/consul4s/commit/761cbf84fb72e382c70193ef2be86f847d8ca4b1)

Thank you!
