### ISSUE TITLE
Can we make Node optional in NewSession ?

### ISSUE THREAD

**Issue by ssahayam-zd** [nryanov/consul4s#131]
Hi,

When creating a new session through the [Session API](https://github.com/nryanov/consul4s/blob/master/modules/core/src/main/scala/consul4s/v1/api/Session.scala#L7), the Node name is mandatory in `NewSession`. 

```scala
def createSession(newSession: NewSession, dc: Option[String] = None, token: Option[String] = None): F[Result[SessionId]]  


final case class NewSession(
  Node: String, //Mandatory
  LockDelay: String,
  Name: Option[String] = None,
  ID: Option[String] = None,
  Checks: Option[List[String]] = Some(List("serfHealth")),
  Behavior: SessionBehavior = SessionBehavior.Release,
  TTL: Option[String] = None
)
```

The Consul API does not require this as mandatory and it can be excluded, such that the requests is submitted to the cluster as opposed to a specific node.

Would be possible to make Node optional in `NewSession`?

```

final case class NewSession(
  Node: Option[String], //Optional
  LockDelay: String,
  Name: Option[String] = None,
  ID: Option[String] = None,
  Checks: Option[List[String]] = Some(List("serfHealth")),
  Behavior: SessionBehavior = SessionBehavior.Release,
  TTL: Option[String] = None
)
```

I'm happy to submit a PR to update this, if this change is acceptable.

**Comment by nryanov** [comment]
@ssahayam-zd Hi!

Good catch, thank you. Happy to merge a fix.

**Comment by ssahayam-zd** [comment]
I just wanted to say that this is an amazingly fast turnaround time for reviewing + merging + releasing this PR. 

Thank you so much! 🥇
