### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by ThuTrinh** [nryanov/consul4s#218]
Hi, is it possible to get a new release published? 
My team uses consul4s and the latest [timepit.refined ](https://github.com/nryanov/consul4s/commit/3a34a2b95a5c28f9c8356564f05037c6ee870e52) bump will unblock us from updating out sbt version.

**Comment by nryanov** [comment]
Hi @ThuTrinh !

Release https://github.com/nryanov/consul4s/releases/tag/v0.6.0 has been published :)

Probably, I should do this more often ^_^

**Comment by ThuTrinh** [comment]
Thanks @nryanov
