### ISSUE TITLE
Upgrade sttp to 3.x

### ISSUE THREAD

**Issue by andreamarcolin** [nryanov/consul4s#9]
It would be nice if sttp could be updated to 3.x :) 
To be fair sttp 3 changed its package name and organization, to allow sttp 2 to be included in projects side by side, so there shouldn't be cases of dependency hell.
Nonetheless I think that depending on the most recent major release could be beneficial in the long term, given that sttp 2 is also unlikely to receive many more updates and backports.

I'm soon going to migrate another project to sttp3, I can help migrating consul4s too after that if there is a desire!

**Comment by nryanov** [comment]
That's' good idea! 
I don't see any obstacles for a such update especially if both versions can co-exist 👍

**Comment by nryanov** [comment]
Released in v.0.3.0 👍
